swagger: "2.0"
info:
  description: "This is LEIA learns server. [Swagger contract](resources/etc/swagger.yaml)."
  version: 1.0.0
  title: LEIA learns
  termsOfService: http://swagger.io/terms/
  contact:
    url: http://leialearns.org/contact/
  license:
    name: LGPLv3
    url: https://www.gnu.org/licenses/lgpl-3.0.en.html
## host: localhost
basePath: /api/greeter
schemes:
- http
consumes: []
produces:
- application/json
paths:
  /api/vocabulary/{key}:
    post:
      tags:
      - LeiaLearns
      description: Create a Vocabulary for symbols
      operationId: createVocabulary
      parameters:
      - in: path
        name: key
        description: The key of the new Vocabulary
        required: true
        type: string
      responses:
        200:
          description: Successful operation
  /api/vocabulary:
    get:
      tags:
      - LeiaLearns
      description: Get the keys of all known vocabularies
      operationId: getVocabularyKeys
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/ArrayOfString"
      produces:
      - application/json
  /api/vocabulary/{key}/symbol/{symbol}:
    post:
      tags:
      - LeiaLearns
      description: Get or create a Symbol in the given Vocabulary
      operationId: getOrCreateSymbol
      parameters:
      - in: path
        name: key
        description: The key of an existing Vocabulary
        required: true
        type: string
      - in: path
        name: symbol
        description: The name of the new Symbol
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/Symbol"
  /api/vocabulary/{key}/symbol:
    get:
      tags:
      - LeiaLearns
      description: Get all symbols in a vocabulary
      operationId: getSymbols
      parameters:
      - in: path
        name: key
        description: The key of an existing Vocabulary
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/ArrayOfSymbol"
  /api/vocabulary/{key}/close:
    post:
      tags:
      - LeiaLearns
      description: Declare this vocabulary closed, no more symbols will be added, description lengths will be determined accordingly
      operationId: closeVocabulary
      parameters:
      - in: path
        name: key
        description: The key of an existing Vocabulary
        required: true
        type: string
      responses:
        200:
          description: Successful operation
  /api/vocabulary/{key}/remain-open:
    post:
      tags:
      - LeiaLearns
      description: Declare that this vocabulary remains open, more symbols can be added later, description lengths will be determined accordingly
      operationId: declareVocabularyOpen
      parameters:
      - in: path
        name: key
        description: The key of an existing Vocabulary
        required: true
        type: string
      responses:
        200:
          description: Successful operation
  /api/vocabulary-upload:
    post:
      tags:
      - LeiaLearns
      description: Upload vocabulary
      operationId: uploadVocabulary
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: data
        description: The data to upload
        type: file
      responses:
        200:
          description: Successful operation
  /api/admin/unique-bucket/clean-existing-keys:
    post:
      tags:
      - LeiaLearns
      description: Move existing keys to their respective child buckets
      operationId: cleanExistingKeys
      responses:
        200:
          description: Successful operation
  /api/admin/unique-bucket:
    get:
      tags:
      - LeiaLearns
      description: Describe all unique buckets
      operationId: describeUniqueBuckets
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/ArrayOfUniqueBucket"
definitions:
  Symbol:
    type: object
    properties:
      vocabulary:
        type: string
      name:
        type: string
      ordinal:
        type: integer
      descriptionLength:
        type: integer
  ArrayOfSymbol:
    type: array
    items:
      $ref: "#/definitions/Symbol"
  UniqueBucket:
    type: object
    properties:
      id:
        type: string
      fullKeyPrefix:
        type: string
      keyPrefix:
        type: string
      parentId:
        type: string
  ArrayOfUniqueBucket:
    type: array
    items:
      $ref: "#/definitions/UniqueBucket"
  ArrayOfString:
    type: array
    items:
      type: string
securityDefinitions:
  STACK_auth:
    type: oauth2
    authorizationUrl: /oauth/authorize
    flow: implicit
    scopes:
      write:LeiaLearns: modify Leia Learns in your account
      read:LeiaLearns: read your Leia Learns
  api_key:
    type: apiKey
    name: api_key
    in: header
