swagger: "2.0"
info:
  description: "This is LEIA learns server. [Swagger contract](resources/etc/swagger.yaml)."
  version: 1.0.0
  title: LEIA learns
  termsOfService: http://swagger.io/terms/
  contact:
    url: http://leialearns.org/contact/
  license:
    name: LGPLv3
    url: https://www.gnu.org/licenses/lgpl-3.0.en.html
## host: localhost
basePath: /api/greeter
schemes:
- http
consumes: []
produces:
- application/json
paths:
  /api/vocabulary/{key}:
    post:
      tags:
      - LeiaLearns
      description: Create a Vocabulary for symbols
      operationId: createVocabulary
      parameters:
      - in: path
        name: key
        description: The key of the new Vocabulary
        required: true
        type: string
      responses:
        200:
          description: Successful operation
  /api/vocabulary/{key}/{symbol}:
    post:
      tags:
      - LeiaLearns
      description: Get or create a Symbol in the given Vocabulary
      operationId: getOrCreateSymbol
      parameters:
      - in: path
        name: key
        description: The key of an existing Vocabulary
        required: true
        type: string
      - in: path
        name: symbol
        description: The name of the new Symbol
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/Symbol"
  /api/prod/{name}:
    post:
      tags:
      - LeiaLearns
      description: Prod the greeter to provoke a response
      operationId: prod
      parameters:
      - in: path
        name: name
        description: The name of the person to greet
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: string
        405:
          description: Invalid input
      security:
      - STACK_auth:
        - write:LeiaLearns
        - read:LeiaLearns
  /api/admin/unique-bucket/clean-existing-keys:
    post:
      tags:
      - LeiaLearns
      description: Move existing keys to their respective child buckets
      operationId: cleanExistingKeys
      responses:
        200:
          description: Successful operation
  /api/admin/unique-bucket:
    get:
      tags:
      - LeiaLearns
      description: Describe all unique buckets
      operationId: describeUniqueBuckets
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/ArrayOfUniqueBucket"
definitions:
  Symbol:
    type: object
    properties:
      name:
        type: string
      ordinal:
        type: integer
      descriptionLength:
        type: integer
  UniqueBucket:
    type: object
    properties:
      id:
        type: string
      fullKeyPrefix:
        type: string
      keyPrefix:
        type: string
      parentId:
        type: string
  ArrayOfUniqueBucket:
    type: array
    items:
      $ref: "#/definitions/UniqueBucket"
securityDefinitions:
  STACK_auth:
    type: oauth2
    authorizationUrl: /oauth/authorize
    flow: implicit
    scopes:
      write:LeiaLearns: modify Leia Learns in your account
      read:LeiaLearns: read your Leia Learns
  api_key:
    type: apiKey
    name: api_key
    in: header
