version: 0.2

env:
  variables:
    DOCKER_HUB_USER: jeroenvm
    IMAGE_VERSION: 0.0.1-SNAPSHOT
  parameter-store:
    DOCKER_HUB_PASSWORD: '****'

phases:
  pre_build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Logging in to Docker Hub...
      - docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASSWORD}"
  build:
    commands:
      - echo "Building LEIA-learns"
      - bin/create-local-settings.sh
      - bin/rebuild.sh -v -v
  post_build:
    commands:
      - docker push "jeroenvm/leia-proxy:${IMAGE_VERSION}"
      - docker push "jeroenvm/leia-core:${IMAGE_VERSION}"
      - docker push "jeroenvm/leia-present:${IMAGE_VERSION}"
      - docker push "jeroenvm/leia-present:${IMAGE_VERSION}-dev"
