#!/usr/bin/false

STACK=leia

AWS_REGION='eu-west-1'
DEPLOY_HOST=localhost
DEPLOY_USER="${USER=guest}"

DOCKER_REPOSITORY='jeroenvm'
STACK_IMAGE_VERSION='0.0.1'
UI_SERVER_PORT='3000'
API_SERVER_PORT='8080'
AXON_SERVER_PORT='8024'
MONGO_VERSION='3.6'
AXON_VERSION='4.0'
DNS_SEARCH='internal.leialearns.org'
