version: '3.3'

networks:
  ${STACK}:
    driver: overlay

services:
  ${STACK}-core:
    image: ${DOCKER_REPOSITORY}/${STACK}-core:${STACK_IMAGE_VERSION}
    hostname: ${STACK}-core
    networks:
    - ${STACK}
    ports:
    - "127.0.0.1:${API_SERVER_PORT}:8080"
  ${STACK}-core-sidecar:
    image: ${DOCKER_REPOSITORY}/${STACK}-core-sidecar:${STACK_IMAGE_VERSION}
    hostname: ${STACK}-core-sidecar
    networks:
    - ${STACK}
    dns_search: ${DNS_SEARCH}
    expose:
    - "8080"
    - "8124"
    - "27017"
    depends_on:
    - ${STACK}-core
