version: '2.4'

networks:
  ${STACK}:
    driver: overlay

services:
  ${STACK}-core:
    image: ${DOCKER_REPOSITORY}/${STACK}-core:${STACK_IMAGE_VERSION}
    hostname: ${STACK}-core
    networks:
    - ${STACK}
  ${STACK}-core-sidecar:
    image: ${DOCKER_REPOSITORY}/${STACK}-core-sidecar:${STACK_IMAGE_VERSION}
    hostname: ${STACK}-core-sidecar
    networks:
    - ${STACK}
    dns_search: ${DNS_SEARCH}
    dns_opt:
    - ndots:1
    ports:
    - "8080:8080"
    expose:
    - "8080"
    - "8124"
    - "27017"
    depends_on:
    - ${STACK}-core
